- name: Configure Redis for clustering
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify:
    - restart redis
  become: yes

- name: Enable Redis service
  systemd:
    name: redis-server
    enabled: yes
    state: started
  become: yes
