- name: Add Redis PPA
  apt_repository:
    repo: ppa:redislabs/redis
    state: present

- name: Install Redis
  apt:
    name: redis
    state: present

- name: Enable Redis service
  systemd:
    name: redis-server
    enabled: yes
    state: started

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  #notify: restart redis
- name: restart redis
  systemd:
    name: redis-server
    state: restarted
