- name: Configure Redis Sentinel
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
  notify: restart sentinel

- name: Change sentinel file permission
  file:
    path: /etc/redis/sentinel.conf
    owner: redis
    group: redis

- name: Create Redis Sentinel systemd service
  template:
    src: redis-sentinel.service.j2
    dest: /etc/systemd/system/redis-sentinel.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Redis Sentinel service
  systemd:
    name: redis-sentinel
    enabled: yes
    state: started
